### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by amjadnoor** [Shubham-Vishwakarma/DotsAndBoxes#1]
@Shubham-Vishwakarma  Can you want to work with our open source organisation [Chryz-hub](https://github.com/orgs/chryz-hub/dashboard). If you want then first you join our [discord](https://discord.gg/jHEYWw6M).

**Comment by Shubham-Vishwakarma** [comment]
@AmjadNoor
Thanks for invitation.
For time been I want to explore more. 
Unfortunately I wont join you officially. I will definitely contribute as much as I can
